### ISSUE TITLE
Stone no longer smelting into Bricks

### ISSUE THREAD

**Issue by TripleKiller666** [renoth/factorio-factory-levels#6] opened 2022-07-23 23:51 UTC
After activating this mod, I can no longer smelt stone into bricks.
It works with a Vanilla smelter, but as soon as it reaches Level 1 it stop accepting Stone.

Disabling this Mod, and only using Vanilla Smelters, I can produce stone bricks just fine, the issue only happens
when I try to use this Mod.

My Active Modlist:
`
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "aai-containers",
      "enabled": true
    },
    
    {
      "name": "aai-industry",
      "enabled": true
    },
    
    {
      "name": "aai-signal-transmission",
      "enabled": true
    },
    
    {
      "name": "Advanced-Drills",
      "enabled": true
    },
    
    {
      "name": "Advanced-Electric-Revamped-v16",
      "enabled": true
    },
    
    {
      "name": "Advanced-Solar-and-Accumulator",
      "enabled": true
    },
    
    {
      "name": "AlertsList2",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "Armored-train",
      "enabled": true
    },
    
    {
      "name": "belt-balancer-performance",
      "enabled": true
    },
    
    {
      "name": "Better-Power-Armor-Grid",
      "enabled": true
    },
    
    {
      "name": "Brighter-Lamps",
      "enabled": true
    },
    
    {
      "name": "bullet-trails",
      "enabled": true
    },
    
    {
      "name": "bzcarbon",
      "enabled": true
    },
    
    {
      "name": "combat-mechanics-overhaul",
      "enabled": true
    },
    
    {
      "name": "extended-descriptions",
      "enabled": true
    },
    
    {
      "name": "factory-levels",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "GUI_Unifyer",
      "enabled": true
    },
    
    {
      "name": "Gun_Turret_Alerts",
      "enabled": true
    },
    
    {
      "name": "informatron",
      "enabled": true
    },
    
    {
      "name": "jetpack",
      "enabled": true
    },
    
    {
      "name": "Kux-OrbitalIonCannon",
      "enabled": true
    },
    
    {
      "name": "laserfence",
      "enabled": true
    },
    
    {
      "name": "LightedPolesPlus",
      "enabled": true
    },
    
    {
      "name": "LoaderRedux",
      "enabled": true
    },
    
    {
      "name": "Long_Range_Radar",
      "enabled": true
    },
    
    {
      "name": "More-Exoskeletons",
      "enabled": true
    },
    
    {
      "name": "more-fusion-reactors",
      "enabled": true
    },
    
    {
      "name": "More_Ammo",
      "enabled": false
    },
    
    {
      "name": "Multiplayer_Scoring",
      "enabled": true
    },
    
    {
      "name": "PavementDriveAssistContinued",
      "enabled": true
    },
    
    {
      "name": "PipeVisualizer",
      "enabled": true
    },
    
    {
      "name": "QueueToFrontNG",
      "enabled": true
    },
    
    {
      "name": "robot_attrition",
      "enabled": true
    },
    
    {
      "name": "RPGsystem",
      "enabled": true
    },
    
    {
      "name": "se-recycling-extras",
      "enabled": true
    },
    
    {
      "name": "SearchlightAssault",
      "enabled": true
    },
    
    {
      "name": "shield-projector",
      "enabled": true
    },
    
    {
      "name": "simhelper",
      "enabled": true
    },
    
    {
      "name": "space-exploration",
      "enabled": true
    },
    
    {
      "name": "space-exploration-graphics",
      "enabled": true
    },
    
    {
      "name": "space-exploration-graphics-2",
      "enabled": true
    },
    
    {
      "name": "space-exploration-graphics-3",
      "enabled": true
    },
    
    {
      "name": "space-exploration-graphics-4",
      "enabled": true
    },
    
    {
      "name": "space-exploration-graphics-5",
      "enabled": true
    },
    
    {
      "name": "space-exploration-menu-simulations",
      "enabled": true
    },
    
    {
      "name": "space-exploration-postprocess",
      "enabled": true
    },
    
    {
      "name": "SpaceLoaderRedux",
      "enabled": true
    },
    
    {
      "name": "specialized-oil-processing",
      "enabled": true
    },
    
    {
      "name": "Squeak Through",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "Story-Missions",
      "enabled": false
    },
    
    {
      "name": "train-pubsub",
      "enabled": true
    },
    
    {
      "name": "TreeSaplings-Redux",
      "enabled": true
    },
    
    {
      "name": "umr",
      "enabled": true
    },
    
    {
      "name": "VehicleTrails",
      "enabled": true
    },
    
    {
      "name": "walls-block-spitters",
      "enabled": true
    },
    
    {
      "name": "Wind_Generator-gfxrestyle",
      "enabled": true
    }
  ]
}
`

**Comment by CaitSith2** [comment] 2022-07-24 01:55
space exploration is the cause.  It created a new crafting category called "kiln".  Knowing this, if the mod checks for space-exploration, it can conditionally add "kiln" to the crafting categories for each of the 25 levels of stone furnace and 100 levels of steel furnace that it creates.

**Comment by renoth** [comment] 2022-07-24 15:10
Thanks for the report and additional info, if space exploration is enabled leveled furnaces now also smelt kiln

**Comment by renoth** [comment] 2022-07-24 15:10
Fixed in 0.2.2

**Closed** 2022-07-24 15:10 UTC
