### ISSUE TITLE
Quality Level is breaking my factory

### ISSUE THREAD

**Issue by Tenderroast** [renoth/factorio-factory-levels#60] opened 2024-10-23 16:43 UTC
The built in quality bonus is breaking my factory in areas certain areas. (such as direct insertion for copper wires to green circuits).

Any chance of adding a toggle for the chance for quality modifiers in those machines?

**Comment by Tenderroast** [comment] 2024-10-23 16:57
Thank you! now to go clean out my factory of quality items that are in the way

**Comment by Valkaziim** [comment] 2024-10-23 17:02
i used the no quality mod, to remove all quality items, then disabled it afterwards, to get a clean base of everything ^^

**Comment by Tenderroast** [comment] 2024-10-23 17:06
i did find an issue tho. When i purposefully made a quality item on a virgin machine, game crashed

**Comment by Tenderroast** [comment] 2024-10-23 17:07
The mod Factory Levels (0.7.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_nth_tick(6)
Invalid ItemID: expected LuaItemPrototype, LuaItemStack, LuaItem or string.
stack traceback:
	[C]: in function 'insert'
	__factory-levels__/control.lua:347: in function 'insert_inventory_contents'
	__factory-levels__/control.lua:415: in function 'upgrade_factory'
	__factory-levels__/control.lua:439: in function 'replace_machines'
	__factory-levels__/control.lua:488: in function <__factory-levels__/control.lua:468>

**Comment by Valkaziim** [comment] 2024-10-23 17:08
Seems like it is the same error i am getting, looks like it cant handle quality items perhaps

**Comment by Tenderroast** [comment] 2024-10-23 17:10
if it is a machine that has already been used just once, to become a level 1, instead of an unleveled machine, then there is no problem at all. The only problem is when it is the very 1st time a machine is being used

**Comment by Valkaziim** [comment] 2024-10-23 17:13
it is odd, but i just found out my issue, it was crafting a beacon which was uncommon, when trying to insert it into a full chest i recieve a crash

**Comment by renoth** [comment] 2024-10-23 17:26
That sounds like an issue with factorio itself

> it is odd, but i just found out my issue, it was crafting a beacon which was uncommon, when trying to insert it into a full chest i recieve a crash

**Comment by renoth** [comment] 2024-10-23 18:48
can you try the latest version 0.7.7`?

**Comment by renoth** [comment] 2024-10-23 18:49
Duplicate of #61

**Closed** 2024-10-23 18:49 UTC
